context:
  url: '#'
  text: Button Label
variants:
  - name: primary
    context:
      modifier: btn--primary
  - name: secondary
    context:
      modifier: btn--secondary
  - name: small
    context:
      modifier: btn--small
  - name: expanded
    context:
      modifier: btn--expanded
